apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: node-container
          image: mahmoudrizk10/nodejsapp
          ports:
            - name: http
              containerPort: 3000
